# Generated by Django 4.1.7 on 2023-03-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfpolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drfpolls.question'),
            preserve_default=False,
        ),
    ]
