# Generated by Django 4.1.7 on 2023-03-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfpolls', '0003_rename_question_comment_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question_id',
            new_name='question',
        ),
    ]
